model_config = {
    'dataset': '../../Data/v2/',
    'level': 'sentences',
    'MAX_LENGTH': 75,
    'embedding_dim': 300,
    'tag_dim': 100,
    'dep_dim': 100,
    'ver':'glove.6B.',
    'freq':0,
    'hidden_size': 256,
    'num_layers': 2,
    'dropout':0.2,
    'lr': 0.001,
    'classifer_class_size': 3,
    'model': 'Attn',
    'batch_size': 32,
    'epochs':10,
    'structural':True,
    'gpu':2,
    'lm_type': 'structural',
    'use_structural_as_standard': False,
    'lm_name': 'gender_male',
    'elmo': False,
    'awd': False,
    'print_every':100
}
